stages:
  - test
  - build


image: node:8.10

before_script:
  - npm install 

test:
  stage: test
  script:
    - npm run test:cov
    
build_dev:
  stage: build
  script:
    - npm run build:dev    
build:
  stage: build
  script:
    - npm run build
    
variables:
  GIT_SSL_NO_VERIFY: "true"
